version: "3.8"

services:
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        # internal only; exposed via nginx
        volumes:
            - ./backend:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./backend/.env
        networks:
            - network

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        # internal only; exposed via nginx
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./frontend/.env
        depends_on:
            - backend
        networks:
            - network

    services:
        container_name: services
        build:
            context: ./services
            dockerfile: Dockerfile
        # internal only; exposed via nginx
        volumes:
            - ./services:/code
        env_file:
            - ./services/.env
        depends_on:
            - backend
        networks:
            - network

    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - frontend
            - backend
            - services
        networks:
            - network
    # default (no profile needed)

networks:
    network:
        driver: bridge
